

#define WM_AP_MOVE		WM_USER+1009
#define WM_AP_LFOOT		WM_USER+1010
#define WM_AP_RFOOT		WM_USER+1011
#define WM_AP_ADVANCE	WM_USER+1012
#define WM_AP_MFOOT		WM_USER+1013
#define WM_AP_MOVE_MT	WM_USER+1014


#define WM_STEREOVIEW_LOADMDL	WM_USER+1020
#define WM_STEREOVIEW_LOADPROJECT	WM_USER+1021

#define FCCM_CLTTOGND		WM_USER+1050
#define FCCM_GNDTOCLT		WM_USER+1051

// 自定义消息
#define FCCM_GETUI			WM_USER+2008
#define FCCM_SHOW_XYZ		WM_USER+2009
#define FCCMD_LOADSTEREO	WM_USER+2010
#define FCCM_LOADPROJECT	WM_USER+2011
#define FCCM_GEOMETRYVIEW	WM_USER+2012
#define FCCM_ATTRIBVIEW		WM_USER+2013
#define FCCM_SETOPTITLE		WM_USER+2014
#define FCCM_PROGRESS		WM_USER+2015
#define FCCM_PROGRESS2		WM_USER+2016
#define FCCM_PRINTSTR		WM_USER+2018
#define FCCM_TRANSLATEMSG	WM_USER+2019
#define FCCM_UPDATEINDICATOR	WM_USER+2020
#define FCCM_UPDATE_ACCUDLG	WM_USER+2021
#define FCCM_SYMBOLLIBVIEW	WM_USER+2022
#define FCCM_SHOW_ACCUDLG	WM_USER+2023
#define FCCM_INITFTRCLASS	WM_USER+2030
#define FCCM_COLLECTIONVIEW	WM_USER+2031
#define FCCM_SETVIEWTYPE	WM_USER+2032
#define FCCM_GETCUSTOMSTATE	WM_USER+2033
#define FCCM_SETCUSTOMSTATE	WM_USER+2034
#define FCCM_GETSENSITIVITY	WM_USER+2035
#define FCCM_GETPROJECT		WM_USER+2036
#define FCCM_SEARCHRESULT	WM_USER+2037
#define FCCM_CUSTOMDLGCLOSE	WM_USER+2038
#define FCCM_GETQUERYMENU	WM_USER+2039
#define FCCM_MODIFY_PROPERTY_UI	WM_USER+2040
#define FCCM_KEYIN          WM_USER+2041
#define FCCM_UPDATEVIEWLIST WM_USER+2042
#define WM_SCHEME_MODIFY    WM_USER+2200
#define WM_SYMBOL_REPAINT   WM_USER+2201
#define FCCM_MODIFYMOUSEPOINT WM_USER+2202
#define FCCM_SETSYMDRAWSCALE WM_USER+2203
#define FCCM_GETDRAWTESTPTBAR WM_USER+2204
#define FCCM_DOCRECREATEFTRS WM_USER+2205
#define FCCM_REFRESHCHKSCHBAR  WM_USER+2206
#define FCCM_CHECKRESULT	WM_USER+2207
#define FCCM_COPYDATA	    WM_USER+2208
#define FCCM_CLOSEDOC		WM_USER+2209
#define FCCM_SETFOCUSCOL    WM_USER+2210
// 内部消息
#define FCCM_GETOPPROPLIST  WM_USER+2040
#define FCCM_UPDATEROPLIST	WM_USER+2041
#define FCCM_GETOPTYPE		WM_USER+2042
#define FCCM_SETOPTYPE		WM_USER+2043
#define FCCM_UPDATEOPPAINT	WM_USER+2044
#define FCCM_GETMDLROTANG   WM_USER+2045
#define FCCM_INITLAYERTOOL	WM_USER+2046
#define FCCM_INITFTRTOOL	WM_USER+2047
#define FCCM_MODIFYFTRCOLOR	WM_USER+2048
#define FCCM_INITLAYVIEWBAR WM_USER+2049
#define FCCM_RESETLAYOUT	WM_USER+2050

#define FCCM_GETMDLBROUND	WM_USER+2060
#define FCCM_GETORTBROUND	WM_USER+2061

#define FCCM_SNAPSTATUS		WM_USER+2062
#define FCCM_INSTANTCMD		WM_USER+2063

#define FCCM_SNAPSETTING	WM_USER+2064
#define FCCM_SELECTSETTING  WM_USER+2065
#define FCCM_UPDATE_ACCUDATA WM_USER+2066
#define FCCM_UPDATESTEREOPARAM		WM_USER+2067
#define FCCM_SHOWEPTOOL		WM_USER+2068
#define FCCM_ADD_RECENTCMD  WM_USER+2069
#define FCCM_LOAD_RECENTCMD  WM_USER+2070
#define FCCM_LOCK_ANGLE		 WM_USER+2071

// 用于符号编辑
#define FCCM_UPDATE_ATOM	WM_USER+2100

// 模型范围图的的消息宏 by shy
#define FCCM_REFRESHVECWIN  WM_USER+2110
#define FCCM_REFRESHCURRENTSTEREOWIN  WM_USER+2111
#define FCCM_REFRESHCURRENTSTEREOMS   WM_USER+2112
#define FCCM_REFRESHVECFLAG   WM_USER+2113
#define FCCM_UNINSTALLPROJ		WM_USER+2114
#define FCCM_SWITCHSTEREOMS    WM_USER+2115  
#define FCCM_GETTOLER          WM_USER+2116
#define FCCM_OPTIONUPDATE        WM_USER+2117

#define FCCM_UPDATE_PROPERTY_UI  WM_USER+2118
#define FCCM_UVS_OPERATECOUNT_CHANGE WM_USER+2533

// ProjectViewBar 的装载标记
#define FCPV_PROJECT		1
#define FCPV_DLGFILE		2
#define FCPV_STEREO			3

// 操作设置的标识
#define FCOP_PLACETEXT		1
#define FCOP_PLACELINES		2
#define FCOP_PLACERECT		4
#define FCOP_PLACEAUTOHEIGHT 5
#define FCOP_BREAK			10
#define FCOP_RECTIFY		11
#define FCOP_EAVESADJUST	12
#define FCOP_REPLACELINES	13
#define FCOP_MODIFYZ		14
#define FCOP_CELLCREATE		15
#define FCOP_COMPRESS		16
#define FCOP_CHANGEFCODE	17
#define FCOP_TRIM			18
#define FCOP_CHANGCONNECT	19
#define FCOP_MOVE			20
#define FCOP_INTERPOLATE	21
#define FCOP_LINKCONTOUR	22
#define FCOP_COMBINE		23
#define FCOP_PLACESURFACE	24
#define FCOP_CHECKLLERROR   25
#define FCOP_CLOSEWITHTOLE	26
#define FCOP_DRAWSECTION	27
#define FCOP_CURPART		28
#define FCOP_EXTEND			29

// 注册的消息

